// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDujdEdrDpYu-kSM8ttKHieGaJFB3dJcSY',
    appId: '1:1055667210231:web:606d8362c5d906adea10f2',
    messagingSenderId: '1055667210231',
    projectId: 'todo-a37c3',
    authDomain: 'todo-a37c3.firebaseapp.com',
    storageBucket: 'todo-a37c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzqyjhHta8iBMDtWlYv1-WnXVTSjkKj80',
    appId: '1:1055667210231:android:4a7292d97d42fcedea10f2',
    messagingSenderId: '1055667210231',
    projectId: 'todo-a37c3',
    storageBucket: 'todo-a37c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRrhYpTp5H9eOXpsS4k-SojfqctljZSZ4',
    appId: '1:1055667210231:ios:8401d7197df35113ea10f2',
    messagingSenderId: '1055667210231',
    projectId: 'todo-a37c3',
    storageBucket: 'todo-a37c3.appspot.com',
    iosBundleId: 'com.example.todoMobxCleanFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRrhYpTp5H9eOXpsS4k-SojfqctljZSZ4',
    appId: '1:1055667210231:ios:030db9cd2e9ff2b3ea10f2',
    messagingSenderId: '1055667210231',
    projectId: 'todo-a37c3',
    storageBucket: 'todo-a37c3.appspot.com',
    iosBundleId: 'com.example.todoMobxCleanFirebase.RunnerTests',
  );
}
